# --- STAGE BUILDER ---
FROM node:18-alpine AS builder

WORKDIR /app

# Copie des dépendances depuis la racine du projet
COPY ../package.json ../package-lock.json ./
RUN npm ci --omit=dev


# --- STAGE PRODUCTION ---
FROM node:22-alpine AS production

WORKDIR /app

# Copie package.json dans l'image (important pour "type": "module")
COPY ../package.json ./

# Copie node_modules
COPY --from=builder /app/node_modules ./node_modules

# Copie le code de l'app
COPY ./app/ ./

EXPOSE 8080

CMD ["node", "server.js"]
